import { Overlay, OverlayContainer, ViewportRuler } from '@angular/cdk/overlay';
import { Platform } from '@angular/cdk/platform';
import { ChangeDetectorRef, OnDestroy, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Article } from '../api/article';
import { HelpExtService } from '../api/help-ext.service';
export declare class HelpExtComponent implements OnDestroy, OnInit {
    private readonly _cdr;
    private readonly _router;
    private readonly _overlay;
    private readonly _api;
    private readonly _viewportRuler;
    private readonly _document;
    private readonly _platform;
    private readonly _overlayContainer;
    private _article;
    get article(): Article;
    set article(value: Article);
    private _routerEventsSubscription;
    private _articleId;
    private _articleUid;
    private _byLocation;
    get articleId(): number;
    set articleId(value: number);
    get articleUid(): string;
    set articleUid(value: string);
    get byLocation(): boolean;
    set byLocation(value: boolean);
    alwaysVisible: boolean;
    inline: boolean;
    private _helpQuestionElement;
    private _overlayRef;
    private _portal;
    private _flyoutInstance;
    private _onDestroy;
    private _showTimeoutId;
    private _hideTimeoutId;
    _onMouseEnter(): void;
    _onMouseLeave(): void;
    private show;
    private hide;
    constructor(_cdr: ChangeDetectorRef, _router: Router, _overlay: Overlay, _api: HelpExtService, _viewportRuler: ViewportRuler, _document: any, _platform: Platform, _overlayContainer: OverlayContainer);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private updateFromLocation;
}
